image: "node:8.16.0-alpine"

stages:
  - test
  - build
  - deploy

before_script:
  - node -v
  - which node
  - npm install

test:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - echo "Building"
    - npm run build

deploy:
  stage: deploy
  script:
    - echo "Building"
    - npm run build
  artifacts:
    paths:
    - public
  only:
  - master

include:
  template: Dependency-Scanning.gitlab-ci.yml
